(setq A (make-array '(3 3 3)))
(setq B (make-array '(3 3 3)))

(dotimes (i 3)
  (dotimes (j 3)
    (dotimes (k 3)
      (setf (aref A i j k) (1+ (random 50)))
      (setf (aref B i j k) (1+ (random 50))))))

(defun print-arr (name arr)
  (format t "~%~A:~%" name)
  (dotimes (i 3)
    (format t " Layer ~A: " i)
    (dotimes (j 3)
      (dotimes (k 3)
        (format t "~4D" (aref arr i j k)))
      (format t "  "))
    (format t "~%")))

(print-arr "A" A)
(print-arr "B" B)

(setq S (make-array '(3 3 3)))
(setq D (make-array '(3 3 3)))
(setq P (make-array '(3 3 3)))
(setq Q (make-array '(3 3 3)))

(dotimes (i 3)
  (dotimes (j 3)
    (dotimes (k 3)
      (setf (aref S i j k) (+ (aref A i j k) (aref B i j k)))
      (setf (aref D i j k) (- (aref A i j k) (aref B i j k)))
      (setf (aref P i j k) (* (aref A i j k) (aref B i j k)))
      (if (zerop (aref B i j k))
          (setf (aref Q i j k) 0)
          (setf (aref Q i j k) (float (/ (aref A i j k) (aref B i j k))))))))

(print-arr "Sum" S)
(print-arr "Difference" D)
(print-arr "Product" P)
(print-arr "Quotient" Q)

(defun arr-stats (name arr)
  (setq elems nil)
  (dotimes (i 3)
    (dotimes (j 3)
      (dotimes (k 3)
        (push (aref arr i j k) elems))))
  (format t "~%~A => Max:~A Min:~A Mean:~,2F~%"
          name (apply #'max elems) (apply #'min elems)
          (/ (apply #'+ elems) 27.0)))

(arr-stats "A" A)
(arr-stats "B" B)
