(setq rules '((malaria   5 (fever headache chills))
               (typhoid   4 (fever headache stomach-pain))
               (flu       3 (fever cough sore-throat))
               (covid     2 (fever cough breathlessness))
               (cold      1 (cough sneezing runny-nose))))

(defun count-matches (rule-symptoms patient-symptoms)
  (let ((count 0))
    (dolist (s rule-symptoms)
      (when (member s patient-symptoms) (incf count)))
    count))

(defun diagnose (symptoms)
  (format t "Symptoms: ~A~%" symptoms)
  (let ((best-name nil) (best-priority -1))
    (dolist (rule rules)
      (let ((name (first rule))
            (priority (second rule))
            (rsymptoms (third rule)))
        (when (and (>= (count-matches rsymptoms symptoms) 2)
                   (> priority best-priority))
          (setq best-name name)
          (setq best-priority priority))))
    (if best-name
        (format t "Primary Diagnosis: ~A (priority ~A)~%" best-name best-priority)
        (format t "No diagnosis found.~%"))))

(diagnose '(fever cough headache chills))
(format t "~%")
(diagnose '(cough sneezing runny-nose))
