(defun flight-advice (budget destination)
  (format t "Budget: ~A, Destination: ~A~%" budget destination)
  (cond
    ((and (< budget 5000) (equal destination 'domestic))
     (format t "  Suggestion: Economy class, budget airline~%"))
    ((and (<= budget 15000) (equal destination 'domestic))
     (format t "  Suggestion: Economy class, regular airline~%"))
    ((and (< budget 15000) (equal destination 'international))
     (format t "  Suggestion: Budget not sufficient for international~%"))
    ((and (<= budget 30000) (equal destination 'international))
     (format t "  Suggestion: Economy class international~%"))
    ((> budget 30000)
     (format t "  Suggestion: Business class~%"))
    (t (format t "  No suggestion.~%"))))

(flight-advice 3000 'domestic)
(format t "~%")
(flight-advice 25000 'international)
(format t "~%")
(flight-advice 50000 'international)
