(setq rules '(("Heart Disease"  0.8 (smoking family-history))
               ("Lung Cancer"    0.7 (smoking exposure-chemicals))
               ("Diabetes"       0.6 (obesity sedentary))
               ("Hypertension"   0.5 (high-salt stress))))

(defun assess-risk (symptoms)
  (format t "Risk factors: ~A~%" symptoms)
  (setq found nil)
  (dolist (rule rules)
    (setq name (first rule))
    (setq cf (second rule))
    (setq conditions (third rule))
    (setq matched 0)
    (dolist (c conditions)
      (when (member c symptoms) (incf matched)))
    (when (>= matched 2)
      (format t "  ~A - Certainty Factor: ~A~%" name cf)
      (setq found t)))
  (when (not found)
    (format t "  No significant risk detected.~%")))

(assess-risk '(smoking family-history))
(format t "~%")
(assess-risk '(obesity sedentary))
(format t "~%")
(assess-risk '(exercise healthy-diet))
