(setq responses '(("hello"   "Hi there! How can I help you?")
                   ("hi"      "Hello! What can I do for you?")
                   ("bye"     "Goodbye! Have a nice day!")
                   ("weather" "It looks sunny today!")
                   ("time"    "I don't have a clock, sorry!")
                   ("help"    "I can chat about weather, time, or just say hi!")))

(defun respond (input)
  (setq input (string-downcase input))
  (setq found nil)
  (dolist (rule responses)
    (when (search (first rule) input)
      (format t "Bot: ~A~%" (second rule))
      (setq found t)
      (return)))
  (when (not found)
    (format t "Bot: I don't understand that.~%")))

(format t "User: Hello~%")
(respond "Hello")
(format t "~%User: What is the weather like?~%")
(respond "What is the weather like?")
(format t "~%User: Bye~%")
(respond "Bye")
(format t "~%User: Tell me a joke~%")
(respond "Tell me a joke")
