(setq facts '((isa socrates man)
               (isa plato man)
               (isa fido dog)
               (all man mortal)
               (all dog animal)
               (all man human)))

(defun is-a (entity category)
  (dolist (f facts)
    (when (and (eq (first f) 'isa)
               (eq (second f) entity)
               (eq (third f) category))
      (return-from is-a t)))
  nil)

(defun has-property (entity prop)
  (dolist (f facts)
    (when (eq (first f) 'all)
      (let ((cat (second f)) (p (third f)))
        (when (and (eq p prop) (is-a entity cat))
          (return-from has-property t)))))
  nil)

(defun check (entity prop)
  (format t "Is ~A ~A? " entity prop)
  (if (has-property entity prop)
      (format t "YES~%")
      (format t "CANNOT DETERMINE~%")))

(format t "Knowledge:~%")
(dolist (f facts) (format t "  ~A~%" f))
(format t "~%")
(check 'socrates 'mortal)
(check 'plato 'human)
(check 'fido 'animal)
(check 'fido 'mortal)
