(setq rules '(("Tandoori Palace" 5 (indian budget high-rating))
               ("Sushi Hub"       4 (japanese moderate good-reviews))
               ("Pizza Corner"    3 (italian budget family))
               ("Dragon Wok"      2 (chinese budget quick-service))
               ("Cafe Latte"      1 (cafe moderate cozy))))

(defun recommend-restaurant (prefs)
  (format t "Preferences: ~A~%" prefs)
  (let ((best nil) (best-pri -1))
    (dolist (rule rules)
      (let ((name (first rule))
            (pri (second rule))
            (conds (third rule))
            (matched 0))
        (dolist (c conds)
          (when (member c prefs) (incf matched)))
        (when (and (>= matched 2) (> pri best-pri))
          (setq best name)
          (setq best-pri pri))))
    (if best
        (format t "  Best match: ~A (priority ~A)~%" best best-pri)
        (format t "  No match found.~%"))))

(recommend-restaurant '(indian budget high-rating))
(format t "~%")
(recommend-restaurant '(italian budget family))
(format t "~%")
(recommend-restaurant '(chinese budget quick-service))
