(defun check-water (ph turbidity)
  (format t "pH: ~A, Turbidity: ~A~%" ph turbidity)
  (cond
    ((< ph 6.5) (format t "  WARNING: Water is acidic~%"))
    ((> ph 8.5) (format t "  WARNING: Water is alkaline~%"))
    (t (format t "  pH is normal~%")))
  (if (> turbidity 5)
      (format t "  ALERT: Water is UNSAFE (high turbidity)~%")
      (format t "  Turbidity is acceptable~%"))
  (if (and (>= ph 6.5) (<= ph 8.5) (<= turbidity 5))
      (format t "  Result: Water is SAFE~%")
      (format t "  Result: Water needs treatment~%")))

(check-water 7.0 3)
(format t "~%")
(check-water 5.0 2)
(format t "~%")
(check-water 7.5 8)
(format t "~%")
(check-water 9.0 6)
