(setq rules '(("Paneer Tikka"    (vegetarian spicy))
               ("Dal Makhani"     (vegetarian mild))
               ("Butter Chicken"  (non-veg mild))
               ("Chicken Vindaloo" (non-veg spicy))
               ("Veg Biryani"     (vegetarian rice-lover))))

(defun recommend (prefs)
  (format t "Preferences: ~A~%" prefs)
  (setq found nil)
  (dolist (rule rules)
    (setq match t)
    (dolist (cond (second rule))
      (when (not (member cond prefs)) (setq match nil)))
    (when match
      (format t "  Recommended: ~A~%" (first rule))
      (setq found t)))
  (when (not found)
    (format t "  No recommendation found.~%")))

(recommend '(vegetarian spicy))
(format t "~%")
(recommend '(non-veg mild))
(format t "~%")
(recommend '(vegetarian rice-lover))
