(setq rules '(("Rice"       (clay monsoon))
               ("Wheat"      (loamy winter))
               ("Watermelon" (sandy summer))
               ("Cotton"     (black summer))
               ("Sugarcane"  (loamy monsoon))))

(defun suggest-crop (soil season)
  (format t "Soil: ~A, Season: ~A~%" soil season)
  (setq found nil)
  (dolist (rule rules)
    (when (and (equal soil (first (second rule)))
               (equal season (second (second rule))))
      (format t "  Suggested crop: ~A~%" (first rule))
      (setq found t)))
  (when (not found)
    (format t "  No crop suggestion available.~%")))

(suggest-crop 'clay 'monsoon)
(format t "~%")
(suggest-crop 'sandy 'summer)
(format t "~%")
(suggest-crop 'loamy 'winter)
