(setq positive-words '("good" "great" "happy" "love" "excellent" "amazing" "wonderful"))
(setq negative-words '("bad" "terrible" "hate" "awful" "horrible" "sad" "angry"))

(defun split-words (text)
  (let ((words nil) (word ""))
    (dotimes (i (length text))
      (let ((ch (char text i)))
        (if (char= ch #\Space)
            (progn (when (> (length word) 0) (push word words)) (setq word ""))
            (setq word (concatenate 'string word (string ch))))))
    (when (> (length word) 0) (push word words))
    words))

(defun analyze (text)
  (format t "Text: ~A~%" text)
  (let ((words (split-words (string-downcase text)))
        (pos 0) (neg 0))
    (dolist (w words)
      (when (member w positive-words :test #'string=) (incf pos))
      (when (member w negative-words :test #'string=) (incf neg)))
    (format t "  Positive: ~A, Negative: ~A~%" pos neg)
    (cond ((> pos neg) (format t "  Sentiment: POSITIVE~%"))
          ((> neg pos) (format t "  Sentiment: NEGATIVE~%"))
          (t (format t "  Sentiment: NEUTRAL~%")))))

(analyze "The movie was great and amazing")
(format t "~%")
(analyze "Terrible food and awful service")
(format t "~%")
(analyze "It was good but also bad")
