(setq rules '(("Radiator issue"      (engine-noise overheating))
               ("Engine mount problem" (engine-noise vibration))
               ("Battery problem"      (wont-start dim-lights))
               ("Brake pad worn"       (squeaking braking-issue))
               ("Flat tire"            (pulling vibration))))

(defun diagnose-car (symptoms)
  (format t "Symptoms: ~A~%" symptoms)
  (setq found nil)
  (dolist (rule rules)
    (setq match t)
    (dolist (s (second rule))
      (when (not (member s symptoms)) (setq match nil)))
    (when match
      (format t "  Diagnosis: ~A~%" (first rule))
      (setq found t)))
  (when (not found)
    (format t "  No diagnosis found.~%")))

(diagnose-car '(engine-noise overheating))
(format t "~%")
(diagnose-car '(wont-start dim-lights))
(format t "~%")
(diagnose-car '(squeaking braking-issue))
